<style>
    .tachado {
        opacity: 0.5;
        color: rgba(0, 0, 0, 0.5);
        font-style: italic;
    }
</style>

<div class="btn-group mb-3" role="group" aria-label="Basic checkbox toggle button group">
    <form id="form-filtro" class="row">
        <select class="form-select col" aria-label="Default select example">
            <option selected>Agrupacion/Tipo</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
        </select>
        <select class="form-select col" aria-label="Default select example">
            <option selected>Zona</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
        </select>
        <select class="form-select col" aria-label="Default select example">
            <option selected>Open this select menu</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
        </select>
        <div class="col">
            <input type="submit" value="Filtrar" class="btn btn-secondary">
        </div>
    </form>

</div>


<table class="table table-bordered">
    <thead>
        <tr class="table-primary">
            <th>ID</th>
            <th>Producto</th>
            <th>Tipo</th>
            <th>Costo</th>
            <th>Cantidad</th>
            <th>Fecha Registro</th>
            <th>Zona</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($registros as $registro): ?>
            <tr class="table-info">
                <td><?= $registro->id ?></td>
                <td><?= $registro->producto ?></td>
                <td><?= $registro->tipo ?></td>
                <td>
                    <?php

                    if ($registro->oferta > $registro->precio) {
                        echo "$" . $registro->precio;
                    } else if ($registro->oferta == 0) {
                        echo "$" . $registro->precio;
                    } else if ($registro->oferta == $registro->precio) {
                        echo "$" . $registro->precio;
                    } else if ($registro->oferta < $registro->precio) {
                        echo "$" . $registro->oferta . " <s class=\"tachado\">$" . $registro->precio . "</s>";
                    }


                    ?>
                </td>

                <td><?= $registro->cantidad ?></td>
                <td><?= $registro->fecha_registro ?></td>
                <td>
                    <?php
                    if ($registro->zona == null) {
                        echo "Desconocido";
                    } else {
                        echo $registro->zona;
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>