<style>
    .tachado {
        color: rgba(0, 0, 0, 0.5);
        font-style: italic;
    }
</style>

<div class="btn-group mb-3" role="group" aria-label="Basic checkbox toggle button group">
    <form id="form-filtro" class="row g-2" method="get" action="">
        <select class="form-select col" name="tipo" aria-label="Default select example">
            <option selected>Agrupacion</option>
            <?php foreach ($tipos as $tipo): ?>
                <option value="<?= $tipo->id_tipo_prod; ?>"><?= $tipo->tipo_prod; ?></option>
            <?php endforeach; ?>
        </select>
        <select class="form-select col" name="zona" aria-label=" Default select example">
            <option selected>Zona</option>
            <?php foreach ($establs as $establ): ?>
                <option value="<?= $establ->id_establ_com; ?>"><?= $establ->zona; ?> - <?= $establ->nombre_establ; ?>
                </option>
            <?php endforeach; ?>
        </select>
        <div class="col-md-4">
            <input type="text" id="producto" name="producto" class="form-control" aria-describedby="producto"
                placeholder="Ingrese nombre producto">
        </div>
        <div class="col">
            <input type="submit" value="Filtrar" class="btn btn-secondary">
        </div>
    </form>
</div>


<table class="table table-bordered">
    <thead>
        <tr class="table-primary">
            <th>ID</th>
            <th>Producto</th>
            <th>Agrupacion</th>
            <th>Costo</th>
            <th>Cantidad</th>
            <th>Fecha Registro</th>
            <th>Zona</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($registros as $registro): ?>
            <tr class="table-info">
                <td><?= $registro->id ?></td>
                <td><?= $registro->producto ?></td>
                <td><?= $registro->tipo ?></td>
                <td>
                    <?php
                    if ($registro->precio == 0) {
                        echo "$" . $registro->oferta;
                    } else if ($registro->oferta > $registro->precio) {
                        echo "$" . $registro->precio;
                    } else if ($registro->oferta == 0) {
                        echo "$" . $registro->precio;
                    } else if ($registro->oferta == $registro->precio) {
                        echo "$" . $registro->precio;
                    } else if ($registro->oferta < $registro->precio) {
                        echo "$" . $registro->oferta . " <s class=\"tachado\">$" . $registro->precio . "</s>";
                    }
                    ?>
                </td>

                <td><?= $registro->cantidad ?></td>
                <td><?= $registro->fecha_registro ?></td>
                <td>
                    <?php
                    if ($registro->zona == null) {
                        echo "Desconocido";
                    } else {
                        echo $registro->zona;
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>

</script>