<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= $this->url('producto') ?>">
                <img src="<?= $this->basePath('img/montaniaLogo.png') ?>" alt="Logo" width="40" height="30"
                    class="d-inline-block align-text-top">
                Señor Montaña
            </a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">otra ocsa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">cosa 2</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>


    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="https://github.com/Rhabad/registro-gastos">Proyecto Rhabad</a> creado por Nicolas... que
                pasaaaaa.
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js')) ?>
</body>

</html>