<h1>Enviar Datos del Usuario</h1>

<form action="<?= $this->url('productoEnviar') ?>" method="post">
    <input type="hidden" name="id" value="">

    <label for="nombreProd">Nombre de Producto:</label>
    <input type="text" id="nombreProd" name="nombreProd" value="">

    <label for="tipoProd">Tipo Producto:</label>
    <input type="text" id="tipoProd" name="tipoProd" value="">

    <label for="precio">Precio:</label>
    <input type="number" id="precio" name="precio" value="0">

    <label for="precioOferta">Precio Oferta:</label>
    <input type="number" id="precioOferta" name="precioOferta" value="0">

    <button type="submit">Enviar</button>
</form>