<h1>Enviar Datos del Usuario</h1>

<form id="form-producto" method="post">
    <input type="hidden" name="id" value="">

    <label for="nombreProd">Nombre de Producto:</label>
    <input type="text" id="nombreProd" name="nombreProd" value="">

    <label for="tipoProd">Tipo Producto:</label>
    <input type="text" id="tipoProd" name="tipoProd" value="">

    <label for="precio">Precio:</label>
    <input type="number" id="precio" name="precio" value="0">

    <label for="precioOferta">Precio Oferta:</label>
    <input type="number" id="precioOferta" name="precioOferta" value="0">

    <button type="submit">Enviar</button>
</form>

<script>

    let form = document.getElementById('form-producto');

    // captura evento de submit
    form.addEventListener('submit', (event) => {
        event.preventDefault(); // evita envio formulario

        const formData = new FormData(form); // obtiene los datos del formulario

        // ruta de envio formulario
        fetch('<?= $this->url('productoEnviar') ?>', {
            method: 'POST',
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                console.log(data);
                form.reset();
            })
            .catch(error => console.error('Error', error));
    });

</script>